# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/quasilyte/CODE/GIT/dipl/Resembler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/quasilyte/CODE/GIT/dipl/Resembler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quasilyte/CODE/GIT/dipl/Resembler/CMakeFiles /home/quasilyte/CODE/GIT/dipl/Resembler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quasilyte/CODE/GIT/dipl/Resembler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Resembler

# Build rule for target.
Resembler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Resembler
.PHONY : Resembler

# fast build rule for target.
Resembler/fast:
	$(MAKE) -f CMakeFiles/Resembler.dir/build.make CMakeFiles/Resembler.dir/build
.PHONY : Resembler/fast

#=============================================================================
# Target rules for targets named headers

# Build rule for target.
headers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 headers
.PHONY : headers

# fast build rule for target.
headers/fast:
	$(MAKE) -f CMakeFiles/headers.dir/build.make CMakeFiles/headers.dir/build
.PHONY : headers/fast

#=============================================================================
# Target rules for targets named rt

# Build rule for target.
rt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rt
.PHONY : rt

# fast build rule for target.
rt/fast:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/build
.PHONY : rt/fast

#=============================================================================
# Target rules for targets named lex

# Build rule for target.
lex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lex
.PHONY : lex

# fast build rule for target.
lex/fast:
	$(MAKE) -f src/lex/CMakeFiles/lex.dir/build.make src/lex/CMakeFiles/lex.dir/build
.PHONY : lex/fast

#=============================================================================
# Target rules for targets named dbg

# Build rule for target.
dbg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dbg
.PHONY : dbg

# fast build rule for target.
dbg/fast:
	$(MAKE) -f src/dbg/CMakeFiles/dbg.dir/build.make src/dbg/CMakeFiles/dbg.dir/build
.PHONY : dbg/fast

#=============================================================================
# Target rules for targets named cc

# Build rule for target.
cc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cc
.PHONY : cc

# fast build rule for target.
cc/fast:
	$(MAKE) -f src/cc/CMakeFiles/cc.dir/build.make src/cc/CMakeFiles/cc.dir/build
.PHONY : cc/fast

#=============================================================================
# Target rules for targets named ast

# Build rule for target.
ast: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ast
.PHONY : ast

# fast build rule for target.
ast/fast:
	$(MAKE) -f src/ast/CMakeFiles/ast.dir/build.make src/ast/CMakeFiles/ast.dir/build
.PHONY : ast/fast

#=============================================================================
# Target rules for targets named io

# Build rule for target.
io: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 io
.PHONY : io

# fast build rule for target.
io/fast:
	$(MAKE) -f src/io/CMakeFiles/io.dir/build.make src/io/CMakeFiles/io.dir/build
.PHONY : io/fast

#=============================================================================
# Target rules for targets named sym

# Build rule for target.
sym: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sym
.PHONY : sym

# fast build rule for target.
sym/fast:
	$(MAKE) -f src/sym/CMakeFiles/sym.dir/build.make src/sym/CMakeFiles/sym.dir/build
.PHONY : sym/fast

#=============================================================================
# Target rules for targets named intrinsic

# Build rule for target.
intrinsic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 intrinsic
.PHONY : intrinsic

# fast build rule for target.
intrinsic/fast:
	$(MAKE) -f src/intrinsic/CMakeFiles/intrinsic.dir/build.make src/intrinsic/CMakeFiles/intrinsic.dir/build
.PHONY : intrinsic/fast

#=============================================================================
# Target rules for targets named dt

# Build rule for target.
dt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dt
.PHONY : dt

# fast build rule for target.
dt/fast:
	$(MAKE) -f src/dt/CMakeFiles/dt.dir/build.make src/dt/CMakeFiles/dt.dir/build
.PHONY : dt/fast

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) -f src/fmt/CMakeFiles/fmt.dir/build.make src/fmt/CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

#=============================================================================
# Target rules for targets named cpp_cg

# Build rule for target.
cpp_cg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpp_cg
.PHONY : cpp_cg

# fast build rule for target.
cpp_cg/fast:
	$(MAKE) -f src/backend/c/cg/CMakeFiles/cpp_cg.dir/build.make src/backend/c/cg/CMakeFiles/cpp_cg.dir/build
.PHONY : cpp_cg/fast

#=============================================================================
# Target rules for targets named go_cc

# Build rule for target.
go_cc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 go_cc
.PHONY : go_cc

# fast build rule for target.
go_cc/fast:
	$(MAKE) -f src/frontend/go_cc/CMakeFiles/go_cc.dir/build.make src/frontend/go_cc/CMakeFiles/go_cc.dir/build
.PHONY : go_cc/fast

#=============================================================================
# Target rules for targets named di

# Build rule for target.
di: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 di
.PHONY : di

# fast build rule for target.
di/fast:
	$(MAKE) -f src/di/CMakeFiles/di.dir/build.make src/di/CMakeFiles/di.dir/build
.PHONY : di/fast

#=============================================================================
# Target rules for targets named unit

# Build rule for target.
unit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit
.PHONY : unit

# fast build rule for target.
unit/fast:
	$(MAKE) -f src/unit/CMakeFiles/unit.dir/build.make src/unit/CMakeFiles/unit.dir/build
.PHONY : unit/fast

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) -f src/app/CMakeFiles/app.dir/build.make src/app/CMakeFiles/app.dir/build
.PHONY : app/fast

#=============================================================================
# Target rules for targets named dt_test

# Build rule for target.
dt_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dt_test
.PHONY : dt_test

# fast build rule for target.
dt_test/fast:
	$(MAKE) -f tests/test_dt/CMakeFiles/dt_test.dir/build.make tests/test_dt/CMakeFiles/dt_test.dir/build
.PHONY : dt_test/fast

#=============================================================================
# Target rules for targets named test_cc

# Build rule for target.
test_cc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_cc
.PHONY : test_cc

# fast build rule for target.
test_cc/fast:
	$(MAKE) -f tests/test_cc/CMakeFiles/test_cc.dir/build.make tests/test_cc/CMakeFiles/test_cc.dir/build
.PHONY : test_cc/fast

lisp.o: lisp.cpp.o
.PHONY : lisp.o

# target to build an object file
lisp.cpp.o:
	$(MAKE) -f CMakeFiles/Resembler.dir/build.make CMakeFiles/Resembler.dir/lisp.cpp.o
.PHONY : lisp.cpp.o

lisp.i: lisp.cpp.i
.PHONY : lisp.i

# target to preprocess a source file
lisp.cpp.i:
	$(MAKE) -f CMakeFiles/Resembler.dir/build.make CMakeFiles/Resembler.dir/lisp.cpp.i
.PHONY : lisp.cpp.i

lisp.s: lisp.cpp.s
.PHONY : lisp.s

# target to generate assembly for a file
lisp.cpp.s:
	$(MAKE) -f CMakeFiles/Resembler.dir/build.make CMakeFiles/Resembler.dir/lisp.cpp.s
.PHONY : lisp.cpp.s

rt.o: rt.cpp.o
.PHONY : rt.o

# target to build an object file
rt.cpp.o:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/rt.cpp.o
.PHONY : rt.cpp.o

rt.i: rt.cpp.i
.PHONY : rt.i

# target to preprocess a source file
rt.cpp.i:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/rt.cpp.i
.PHONY : rt.cpp.i

rt.s: rt.cpp.s
.PHONY : rt.s

# target to generate assembly for a file
rt.cpp.s:
	$(MAKE) -f CMakeFiles/rt.dir/build.make CMakeFiles/rt.dir/rt.cpp.s
.PHONY : rt.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Resembler"
	@echo "... edit_cache"
	@echo "... headers"
	@echo "... rebuild_cache"
	@echo "... rt"
	@echo "... test"
	@echo "... lex"
	@echo "... dbg"
	@echo "... cc"
	@echo "... ast"
	@echo "... io"
	@echo "... sym"
	@echo "... intrinsic"
	@echo "... dt"
	@echo "... fmt"
	@echo "... cpp_cg"
	@echo "... go_cc"
	@echo "... di"
	@echo "... unit"
	@echo "... app"
	@echo "... dt_test"
	@echo "... test_cc"
	@echo "... lisp.o"
	@echo "... lisp.i"
	@echo "... lisp.s"
	@echo "... rt.o"
	@echo "... rt.i"
	@echo "... rt.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

