#!/bin/bash

delimeter() {
    echo "----------------------------------------------------\\"
    echo -e "\t[[ $1 ]]"
    echo "----------------------------------------------------/"
}

delimeter "BUILD"

make

if [[ $? = "0" ]]; then
    clear
    delimeter "RUN"
    ./bin/resembler
fi;
