#pragma once

#include <stdint.h>

typedef int64_t Int_;
typedef double Real_;

// Everything below is not a "core" and will should be generated by backend
// instead of being predefined here

inline Int_ real_to_int_(Real_ x) { return (Int_)x; }

inline Real_ int_to_real_(Int_ x) { return (Real_)x; }

